### ISSUE TITLE
Front-end with Amplify

### ISSUE THREAD

**Issue by zachjonesnoel** [aws-samples/serverless-coffee#3]
I know the front-end is been reworked upon can this be with Amplify so that the backend is maintained by SAM CLI and front-end with Amplify? and hosted with Amplify over CloudFront?

**Comment by StasonJatham** [comment]
Hello! 

what you describe is actually how the old version already worked.

here is the "old" front-end code
https://github.com/aws-samples/serverless-coffee-workshop/tree/main/frontends

and here the workshop to build this:
https://workshop.serverlesscoffee.com/0-introduction.html

and here the website:
https://serverlessland.com/reinvent2021/serverlesspresso
