### ISSUE TITLE
CDK please 

### ISSUE THREAD

**Issue by entest-hai** [aws-samples/serverless-coffee#4]
1. Please replace the template.yaml by cdk stack.ts which are much more friendly to digest.
2. Why not using Amplify pub/sub instead of AWS IoT? 
3. The workshop diagram show 2 API GW. Are there 1 or 2 API GW?

**Comment by jbesw** [comment]
Hello - we have no plans to implement CDK at this stage, but I'll add to the backlog. This project does not use Amplify but you are welcome to use as an alternative. There are two API GW endpoints in use.
